# View Protocol documentation and information about the mod here:
# https://github.com/Noxcrew/noxesium/wiki

# Add some extra output for debugging purposes
extraDebugOutput: false

# If true will check the plugin's version once in a while.
checkForUpdates: true

# It true will send defaults to Noxesium Players on join.
sendDefaultsOnJoin: false

# Comment out the line if you don't want to send that rule.
defaults:
  #cameraLocked: false
  #disableBoatCollisions: false
  #disableDeferredChunkUpdates: false
  #disableMapUi: false
  #disableSpinAttackCollisions: false
  #disableUiOptimizations: false
  #disableVanillaMusic: false
  #enableSmootherClientTrident: false
  #heldItemNameOffset: 0
  #handItemOverride: 'minecraft:stick[minecraft:enchantments={levels:{"minecraft:knockback":25}}]'
  #overrideGraphicsMode: FAST
  #riptideCoyoteTime: 0
  #showMapInUi: false
  #customCreativeItems: false
  #qibBehaviors: []

#qibDefinitions: 
#  example:
#    onEnter: 'example_qib_enter.json'
#    onLeave: 'example_qib_leave.json'
#    triggerEnterLeaveOnSwitch: false

#customCreativeItems:
#  - 'minecraft:stick[minecraft:enchantments={levels:{"minecraft:knockback":25}}]'